UDP_INPUT_IID_SERVER_IP = "192.168.0.136"
UDP_INPUT_IID_SERVER_PORT = 7000

WIFI_SSID = "OfflineCodeTournament2G"
WIFI_PASSWORD = "12345678"
MQTT_BROKER = "192.168.0.136"
MQTT_PORT = 1883
MQTT_TOPIC_IMPORT_CODE = "read_only/code_to_run"
MQTT_TOPIC_RECOVERT_GAME_INFO = "read_only/game_information"
MQTT_YOUR_CLIENT_NAME = "PICO_W2"